### ISSUE TITLE
Position issue on resize

### ISSUE THREAD

**Issue by Eloquent7** [andreas-pihlstrom/Nested#16]
![screen shot 2013-07-23 at 11 46 55](https://f.cloud.github.com/assets/1927482/840774/2440aa78-f37d-11e2-9964-aeaf7d919ccc.png)

Is it possible to keep the grid in place when the browser resizes?

**Comment by gablabelle** [comment]
I'm having the same problem. When resizing the window the container (with margin: 0 auto;) will stay in the center but the boxes will not move.

The site from which I discovered jQuery Nested (http://mamo.fr/) seems to have this issue fixed. I'm not a coder, so it's hard for me to read the code and understand what has been done to fix this.

Any solution?

**Comment by gablabelle** [comment]
It seems like the plugin will position the boxes according to the absolute position of the nested container when the page is loaded. So when we resize the window, since the boxes uses the initial absolute position of the nested container, they simply don't move.

If you set the nested container's position css property to 'relative', you will see that the boxes will position themselves according to the container and will move when you resize the window. But they are at wrong place since the data-y and data-x should now be calculated from top and left of the nested container instead of the top and left of body or html document.

**Comment by gablabelle** [comment]
@Eloquent7 Following my previous post, I added a relative position css property to the nested container and modify the code a bit. Starting at line 345. Problem solved.

``` javascript
        _pushItem: function ($el, x, y, w, h, cols, rows, method) {

            if (method == "prepend") {
                this.elements.unshift({
                    $el: $el,
                    //x: x + this.box.offset().left,
                    //y: y + this.box.offset().top,
                    x: x + 0,
                    y: y + 0,
                    width: w,
                    height: h,
                    cols: cols,
                    rows: rows
                });
            } else {
                this.elements.push({
                    $el: $el,
                    //x: x + this.box.offset().left,
                    //y: y + this.box.offset().top,
                    x: x + 0,
                    y: y + 0,
                    width: w,
                    height: h,
                    cols: cols,
                    rows: rows
                });
            }
        },
```

**Comment by Eloquent7** [comment]
Awesome, your fix works! 
Thanks a lot!

**Comment by akinadebowale** [comment]
@gablabelle - Thanks bro.

**Comment by akinadebowale** [comment]
To remove the jerk, set animation to to false and see the small amendment to @gablabelle code below. Hope to see in next update.

<pre><code>
        _pushItem: function ($el, x, y, w, h, cols, rows, method) {
            if (method == "prepend") {
                this.elements.unshift({
                    $el: $el,
                    x: x, //+ this.box.position().left,
                    y: y, //+ this.box.position().top, 
                    width: w,
                    height: h,
                    cols: cols,
                    rows: rows
                });
            } else {
                this.elements.push({
                    $el: $el,
                    x: x, //+ this.box.position().left,
                    y: y, //+ this.box.position().top, 
                    width: w,
                    height: h,
                    cols: cols,
                    rows: rows
                });
            }
        },
</code></pre>

**Comment by mediastuttgart** [comment]
for a proper container height you should also comment out a part of line 374

``` javascript
var colY = (value['y'] + value['height']) /*- self.box.offset().top */;
```
