### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by reardestani** [andreas-pihlstrom/Nested#25]
Hi,

Thanks for this great plugin.

I am implementing this into a template and I faced two issues:
1. The first item has problem in position and it will stick to right or bottom items.( It is ok in firefox but in chrome it happens - I use latest versions of browsers)
2. It crashes a lot when I resize my browser.

You can check your own demo to see these issues and following image is from your own demo:
![image](https://f.cloud.github.com/assets/2968507/1501447/bdf1fd1c-488b-11e3-8bd8-01a75f3142a7.png)

**Comment by reardestani** [comment]
I am still wating for fixes.

**Comment by andreas-pihlstrom** [comment]
None of these issues shows up in Chrome (Version 30.0.1599.101) for me.

**Comment by reardestani** [comment]
I use Chrome (Version 30.0.1599.101 m) too, the below image is the page I see in my Chrome. I also used it in my page and it has the same issue. 

![image](https://f.cloud.github.com/assets/2968507/1508791/59d3c4d8-4a1a-11e3-99ef-4a33953cce54.png)

**Comment by reardestani** [comment]
It is solved. I have putted my items in a container which had padding. the padding causes the issue.

Regards,
